import { spawnSync } from "child_process";
import fs from "fs";
import path from "path";

const root = process.cwd();
const defaultInput = path.join(root, "data/strategy-library/review-batch-001.jsonl");

function parseArgs(argv) {
  const options = {
    batch: "review-001",
    approvedBy: "pending-review",
    output: null,
    replace: false,
    inputs: [],
  };

  for (const arg of argv) {
    if (arg.startsWith("--batch=")) options.batch = arg.slice("--batch=".length);
    else if (arg.startsWith("--approved-by=")) options.approvedBy = arg.slice("--approved-by=".length);
    else if (arg.startsWith("--output=")) options.output = path.resolve(root, arg.slice("--output=".length));
    else if (arg === "--replace") options.replace = true;
    else options.inputs.push(path.resolve(root, arg));
  }

  if (options.inputs.length === 0) options.inputs = [defaultInput];
  if (!options.output) {
    options.output = path.join(root, `data/strategy-library/import/${options.batch}.sql`);
  }

  return options;
}

function sql(value) {
  if (value === undefined || value === null) return "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

function jsonSql(value) {
  return sql(JSON.stringify(value ?? []));
}

function readJsonl(filePath) {
  return fs.readFileSync(filePath, "utf8")
    .trim()
    .split("\n")
    .filter(Boolean)
    .map(line => JSON.parse(line));
}

function validateFirst(inputs) {
  const validator = path.join(root, "scripts/strategy-library/validate_strategy_library.mjs");
  const result = spawnSync(process.execPath, [validator, ...inputs], {
    cwd: root,
    encoding: "utf8",
  });

  if (result.stdout) process.stdout.write(result.stdout);
  if (result.stderr) process.stderr.write(result.stderr);
  if (result.status !== 0) {
    throw new Error("Import SQL was not created because validation failed.");
  }
}

function insertStatement(block, options) {
  const command = options.replace ? "INSERT OR REPLACE" : "INSERT";
  const values = [
    sql(block.id),
    sql(block.title),
    sql(block.domain),
    sql(block.section_type),
    sql(JSON.stringify(block.content_json)),
    jsonSql(block.category_tags),
    jsonSql(block.launch_status_tags),
    jsonSql(block.audience_tags),
    jsonSql(block.platform_tags),
    jsonSql(block.product_type_tags),
    jsonSql(block.business_model_tags),
    jsonSql(block.goal_tags),
    jsonSql(block.budget_tags),
    jsonSql(block.location_tags),
    jsonSql(block.problem_tags),
    sql(block.difficulty),
    sql(block.priority),
    sql(block.timeframe),
    Number(block.quality_score || 0),
    sql(block.language_level || "beginner"),
    block.active ? 1 : 0,
    sql(block.version || "1.0.0"),
    sql(options.batch),
    sql(options.approvedBy),
  ];

  return `${command} INTO strategy_blocks (
  id, title, domain, section_type, content_json,
  category_tags, launch_status_tags, audience_tags, platform_tags,
  product_type_tags, business_model_tags, goal_tags, budget_tags,
  location_tags, problem_tags, difficulty, priority, timeframe,
  quality_score, language_level, active, version, source_batch, approved_by
) VALUES (${values.join(", ")});`;
}

function buildSql(blocks, options, sourceFiles) {
  const activeBlocks = blocks.filter(block => block.active && Number(block.quality_score) >= 4);
  const importId = `strategy-import-${options.batch}`;
  const sourceLabel = sourceFiles.map(filePath => path.relative(root, filePath)).join(",");
  const qualityReport = {
    source: "scripts/strategy-library/validate_strategy_library.mjs",
    expected_status: "ok",
    active_blocks: activeBlocks.length,
    total_blocks: blocks.length,
  };

  return [
    "-- Generated by scripts/strategy-library/build_import_sql.mjs",
    "-- Review this file before running it against D1.",
    "BEGIN TRANSACTION;",
    "",
    ...activeBlocks.map(block => insertStatement(block, options)),
    "",
    `${options.replace ? "INSERT OR REPLACE" : "INSERT"} INTO strategy_library_imports (
  id, batch_name, source_file, total_blocks, active_blocks, rejected_blocks, imported_by, quality_report_json
) VALUES (
  ${sql(importId)}, ${sql(options.batch)}, ${sql(sourceLabel)}, ${blocks.length},
  ${activeBlocks.length}, ${blocks.length - activeBlocks.length}, ${sql(options.approvedBy)},
  ${sql(JSON.stringify(qualityReport))}
);`,
    "",
    "COMMIT;",
    "",
  ].join("\n");
}

const options = parseArgs(process.argv.slice(2));

validateFirst(options.inputs);

const blocks = options.inputs.flatMap(readJsonl);
const sqlText = buildSql(blocks, options, options.inputs);

fs.mkdirSync(path.dirname(options.output), { recursive: true });
fs.writeFileSync(options.output, sqlText);

console.log(JSON.stringify({
  ok: true,
  dryRunOnly: true,
  message: "SQL file created. It has not been executed against D1.",
  inputFiles: options.inputs.map(filePath => path.relative(root, filePath)),
  totalBlocks: blocks.length,
  activeBlocks: blocks.filter(block => block.active && Number(block.quality_score) >= 4).length,
  output: path.relative(root, options.output),
}, null, 2));
